stages:
  - ci
  - deploy
  - rm

variables:
  IMG_NAME: nx-tools
  REG_HOST: docker-registry:443/embedded
  BUILD_CONTEXT: /locod/docker/nx/

build-ci-docker:
  stage: ci
  tags:
    - docker-build

  script:
    - docker build -t ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} -f Dockerfile ${BUILD_CONTEXT}
    - docker run --rm -u $(id -u):$(id -g) --hostname localhost.localdomain --mac-address 86:8a:dd:8d:51:a8 -t ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} bash -c 'lmgrd;sleep 1;nxpython --version'

build-deploy:
  stage: deploy
  tags:
    - docker-build
  only:
    - tags

  script:
    - docker tag ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME} ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG 
    - docker image tag ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG ${REG_HOST}/${IMG_NAME}:latest
    - docker push ${REG_HOST}/${IMG_NAME}:latest
    - docker push ${REG_HOST}/${IMG_NAME}:$CI_COMMIT_TAG

remove-tmp-img:
  stage: rm
  tags:
    - docker-build

  script:
    - docker image rm ${IMG_NAME}_ci:ci-${CI_COMMIT_REF_NAME}
